### ISSUE TITLE
bot.reply() Unknown Channel

### ISSUE THREAD

**Issue by Haijo7** [brainboxdotcc/DPP#271] opened 2022-02-12 16:10 UTC
When calling the reply function in dpp::cluster the callback contains an error with the message "Unknown Channel" and doesn't send the reply. there is nothing in error_info.

**To Reproduce**
```
void Roles(const dpp::message_create_t &event)
{
    bot.roles_get(event.msg.guild_id, [&](const dpp::confirmation_callback_t &confm)
    {
        if (confm.is_error())
        {
            std::string err = confm.get_error().message;
            std::cout << "get_roles: " << err << std::endl;
            throw err;
        }

        dpp::role_map allRoles = std::get<dpp::role_map>(confm.value);

        std::string roleText = "\\";

        for (auto it = allRoles.begin(); it != allRoles.end(); it++)
            roleText = it->second.name + "\n" + roleText;

        event.reply(roleText, 0, [&](const dpp::confirmation_callback_t &rply)
        {
            if (rply.is_error())
            {
                dpp::error_info err = rply.get_error();
                std::cout << "reply: " << err.message << std::endl;

                std::vector<dpp::error_detail> detail = err.errors;

                for (auto it = detail.begin(); it != detail.end(); it++)
                    std::cout << &it->code << ": " << &it->field << ": " << &it->object << ": " << &it->reason << std::endl;

                throw err.message;
            }
        });

        std::cout << roleText << std::endl;
    });
}
```

**System Details:**
 - OS: Arch Linux (5.16.8-arch1-1)

**Additional context**
Other similar functions that call reply() *do* work, for example:
```
void Repeat(const dpp::message_create_t &event)
{
    std::string input = sliceString(event.msg.content, sizeof("!repeat"));

    event.reply("```" + input + "```");
}
```

**Comment by Axyte** [comment] 2022-02-12 16:18
Not a bug. The captured reference will be invalidated by the time of calling. 
Read about it here:
https://dpp.dev/lambdas-and-locals.html

**Closed** 2022-02-12 17:43 UTC
Labels: bug, invalid
